# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\xc0\x01\n\nSmallProto\x12\n\n\x02i1\x18\x01 \x01(\x03\x12\n\n\x02i2\x18\x02 \x01(\x03\x12\n\n\x02i3\x18\x03 \x01(\x03\x12\n\n\x02i4\x18\x04 \x01(\x03\x12\n\n\x02i5\x18\x05 \x01(\x03\x12\n\n\x02\x66\x31\x18\x06 \x01(\x01\x12\n\n\x02\x66\x32\x18\x07 \x01(\x01\x12\n\n\x02\x66\x33\x18\x08 \x01(\x01\x12\n\n\x02\x66\x34\x18\t \x01(\x01\x12\n\n\x02\x66\x35\x18\n \x01(\x01\x12\n\n\x02s1\x18\x0b \x01(\t\x12\n\n\x02s2\x18\x0c \x01(\t\x12\n\n\x02s3\x18\r \x01(\t\x12\n\n\x02s4\x18\x0e \x01(\t\x12\n\n\x02s5\x18\x0f \x01(\t\"}\n\x0fMediumItemProto\x12\n\n\x02i1\x18\x01 \x01(\x03\x12\n\n\x02i2\x18\x02 \x01(\x03\x12\n\n\x02i3\x18\x03 \x01(\x03\x12\n\n\x02\x66\x31\x18\x04 \x01(\x01\x12\n\n\x02\x66\x32\x18\x05 \x01(\x01\x12\n\n\x02\x66\x33\x18\x06 \x01(\x01\x12\n\n\x02s1\x18\x07 \x01(\t\x12\n\n\x02s2\x18\x08 \x01(\t\x12\n\n\x02s3\x18\t \x01(\t\"\x1a\n\x08TupleKey\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\xde\x02\n\x0bMediumProto\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.MediumItemProto\x12&\n\x05\x64ict1\x18\x02 \x03(\x0b\x32\x17.MediumProto.Dict1Entry\x12&\n\x05\x64ict2\x18\x03 \x03(\x0b\x32\x17.MediumProto.Dict2Entry\x12&\n\x05\x64ict3\x18\x04 \x03(\x0b\x32\x17.MediumProto.Dict3Entry\x1a\x39\n\nDict1Entry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.SmallProto:\x02\x38\x01\x1a@\n\nDict2Entry\x12\x16\n\x03key\x18\x01 \x01(\x0b\x32\t.TupleKey\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.SmallProto\x1a\x39\n\nDict3Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.SmallProto:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIUMPROTO_DICT1ENTRY']._loaded_options = None
  _globals['_MEDIUMPROTO_DICT1ENTRY']._serialized_options = b'8\001'
  _globals['_MEDIUMPROTO_DICT3ENTRY']._loaded_options = None
  _globals['_MEDIUMPROTO_DICT3ENTRY']._serialized_options = b'8\001'
  _globals['_SMALLPROTO']._serialized_start=17
  _globals['_SMALLPROTO']._serialized_end=209
  _globals['_MEDIUMITEMPROTO']._serialized_start=211
  _globals['_MEDIUMITEMPROTO']._serialized_end=336
  _globals['_TUPLEKEY']._serialized_start=338
  _globals['_TUPLEKEY']._serialized_end=364
  _globals['_MEDIUMPROTO']._serialized_start=367
  _globals['_MEDIUMPROTO']._serialized_end=717
  _globals['_MEDIUMPROTO_DICT1ENTRY']._serialized_start=535
  _globals['_MEDIUMPROTO_DICT1ENTRY']._serialized_end=592
  _globals['_MEDIUMPROTO_DICT2ENTRY']._serialized_start=594
  _globals['_MEDIUMPROTO_DICT2ENTRY']._serialized_end=658
  _globals['_MEDIUMPROTO_DICT3ENTRY']._serialized_start=660
  _globals['_MEDIUMPROTO_DICT3ENTRY']._serialized_end=717
# @@protoc_insertion_point(module_scope)
