val:
    cd pyeval-core && cargo test
    cargo check
    maturin develop
    uv run --python 3.13 pytest
    uv run --python 3.13 ruff check .

clean:
    cargo clean
    find . -type d -name "__pycache__" -exec rm -rf {} +
    find . -type d -name ".pytest_cache" -exec rm -rf {} +
    find . -type d -name ".ruff_cache" -exec rm -rf {} +
