proto:
    uv run python -m grpc_tools.protoc -Isrc/pyser --python_out=src/pyser src/pyser/schema.proto

val: proto
    uv run ruff check .
    uv run ty check
    uv run pytest

clean:
    rm -f src/pyser/schema_pb2.py
    find . -type d -name "__pycache__" -exec rm -rf {} +
    find . -type d -name ".pytest_cache" -exec rm -rf {} +
    find . -type d -name ".ruff_cache" -exec rm -rf {} +
