[package]
name = "cashme"
version = "0.1.0"
edition = "2021"

[lib]
name = "cashme"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cashme-cli"
path = "src/main.rs"

[dependencies]
# TODO we disable extension-module so that `cargo build` works on mac (otherwise it complaints about symbol issues). But that links the cli app to python on mac which is undesirable!
# pyo3 = { version = "0.23", features = ["extension-module"] }
pyo3 = { version = "0.23" }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
