test-py:
    # TODO this implicitly depends on rust build having happened -- fix!
    uv run maturin develop
    uv run ruff check .
    uv run pytest

test-rs:
    cargo check
    cargo test

build:
    cargo build --release -p cashme-cli
    cp target/release/cashme-cli python/cashme/
    uv run maturin build --release

val: test-rs test-py

clean:
    cargo clean
    find . -type d -name "__pycache__" -exec rm -rf {} +
    find . -type d -name ".pytest_cache" -exec rm -rf {} +
    find . -type d -name ".ruff_cache" -exec rm -rf {} +
