test-py:
    uv run maturin develop
    uv run ruff check .
    uv run pytest

test-rs:
    cargo check
    cargo test

build:
    cargo build --release --bin cashme-cli
    cp target/release/cashme-cli python/cashme/
    uv run maturin build --release

val: test-rs test-py

clean:
    cargo clean
